# Generated by Django 4.2.3 on 2023-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('meta_intake_vasos', models.PositiveIntegerField()),
                ('vasos_tomados', models.PositiveIntegerField(default=0)),
                ('notificacion', models.BooleanField(default=False)),
                ('realizado', models.BooleanField(default=False)),
            ],
        ),
    ]
