# Generated by Django 4.2.3 on 2023-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('tipo', models.CharField(choices=[('cardio', 'Cardio'), ('muscular', 'Muscular')], max_length=10)),
                ('notificacion', models.BooleanField(default=False)),
                ('realizado', models.BooleanField(default=False)),
            ],
        ),
    ]
